MyClosetWeb Codigo/MyClosetWeb/Models/Closet.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyClosetWeb.Models
{
    public class Closet
    {
        [Key]
        public int ClosetId { get; set; }
        public List<Clothes> Clothes { get; set; }
       
        public Closet()
        {
            Clothes = new List<Clothes>();
        }

        [ForeignKey("User")]
        public int UserId { get; set; }
        public User User { get; set; }
    }
}

MyClosetWeb Codigo/MyClosetWeb/Models/ClotheType.cs
namespace MyClosetWeb.Models
{
    public enum ClotheType
    {
        MangaLonga,
        Cropped,
        Regata,
        Calca,
        Saia,
        Shorts,
        Legging,
        Puffer,
        Jaqueta,
        Casaco,
        Trico,
        Moletom,
        Relogio,
        Bolsa,
        Bag,
        Bone
    }
}

MyClosetWeb Codigo/MyClosetWeb/Models/Clothes.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyClosetWeb.Models
{
    public class Clothes
    {
        [Key]
        public int ClothId { get; set; }
        public string Nickname { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public TissueType Tissue { get; set; }
        public ClotheType Type { get; set; }
        public string Image { get; set; }
        
        [NotMapped] 
        public IFormFile ImageFile { get; set; }
    }
}

MyClosetWeb Codigo/MyClosetWeb/Models/ErrorViewModel.cs
namespace MyClosetWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyClosetWeb Codigo/MyClosetWeb/Models/TissueType.cs
namespace MyClosetWeb.Models
{
    public enum TissueType
    {
        Clotch,
        Jeans,
        Poliester,
        Paete
    }
}

MyClosetWeb Codigo/MyClosetWeb/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace MyClosetWeb.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }
        public string Name { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }
    }
}

MyClosetWeb Codigo/MyClosetWeb/Controllers/ClosetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyClosetWeb.Data;
using MyClosetWeb.Models;
using Newtonsoft.Json;
using System.IO;
namespace MyClosetWeb.Controllers
{
    public class ClosetController : Controller
    {
        private readonly DataContext _context;
        public User CurrentUser { get; set; }
        public Closet UserCloset { get; set; }

        public ClosetController(DataContext context)
        {
            _context = context;
        }

        public IActionResult LoadUser(User currentUser)
        {
            string userJson = (string)TempData["LoggedUser"];
            if(userJson is not null)
            {
                CurrentUser = JsonConvert.DeserializeObject<User>(userJson);
                ViewBag.CurrentUser = CurrentUser;
                TempData["userId"] = CurrentUser.UserId;
                LoadCLoset(CurrentUser.UserId);

                return View("Closet");
            }
            return Index();
        }

        private void LoadCLoset(int userId)
        {
            UserCloset = _context.Closet.Include(c => c.User)
                                                        .Include(c => c.Clothes)
                                                        .FirstOrDefault(c => c.UserId == userId);
                                                   
            if (UserCloset is not null)
            {
                
                
                
                
                ViewBag.UserCloset = UserCloset;
            }
        }

        [HttpPost]
        public IActionResult RegisterCloset(Clothes newCloth)
        {
            var userId = (int)TempData["userId"];
            LoadCLoset(userId);
            if (UserCloset is null)
            {
               UserCloset = new Closet();

            }

            if (userId !=0)
            {
                newCloth.Image = ConvertImageToBase64(newCloth.ImageFile);
                UserCloset.Clothes.Add(newCloth);
                UserCloset.UserId = userId;            
                _context.Closet.Update(UserCloset);
                _context.SaveChanges();
            }
            return View("Closet");
        }
        public ActionResult Index()
        {
            return View("~/Views/Home/Index.cshtml");
        }

        public string ConvertImageToBase64(IFormFile imageFile)
        {
            if (imageFile != null && imageFile.Length > 0)
            {
                
                using (var memoryStream = new MemoryStream())
                {
                    imageFile.CopyTo(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();
                    string base64String = Convert.ToBase64String(imageBytes);
                    return base64String;
                }
            }
            return string.Empty;
        }

        public IActionResult ExcluirPeca(int clothId)
        {
           
            var cloth = dbContext.Clothes.Find(clothId);
            if (cloth != null)
            {
                dbContext.Clothes.Remove(cloth);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

MyClosetWeb Codigo/MyClosetWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyClosetWeb.Models;
using System.Diagnostics;

namespace MyClosetWeb.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public ActionResult RegisterPage()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyClosetWeb Codigo/MyClosetWeb/Controllers/RegisterPageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyClosetWeb.Data;
using MyClosetWeb.Models;
using Newtonsoft.Json;
using System.Reflection.Metadata;

namespace MyClosetWeb.Controllers
{
    public class RegisterPageController : Controller
    {
        private readonly DataContext _context;

        public RegisterPageController(DataContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult RegisterPage(User newUser)
        {            
            if (ModelState.IsValid)
            {                
                _context.Users.Add(newUser);
                _context.SaveChanges();
                return Closet();
            }
            return View(newUser);
        }        
        [HttpPost]
        public IActionResult CheckUser(User User)
        {

            var isUserRegistred = _context.Users.FirstOrDefault(u => u.Email.Equals(User.Email)
                                                    && u.Password.Equals(u.Password));
            if (isUserRegistred is not null)
            {
                string userJson = JsonConvert.SerializeObject(isUserRegistred);

                TempData["LoggedUser"] = userJson;

                return RedirectToAction("LoadUser", "Closet");
            }

            return Register();
        }

        // GET: RegisterController
        public ActionResult Index()
        {
            return View("~/Views/Home/Index.cshtml");
        }         
        public ActionResult Register()
        {
            return View("~/Views/Home/RegisterPage.cshtml");
        }             
        public ActionResult Closet()
        {
            return View("~/Views/Closet/Closet.cshtml");
        }        
    }
}

MyClosetWeb Codigo/MyClosetWeb/Views/Closet/Closet.cshtml
@model MyClosetWeb.Models.Clothes

@{
    ViewData["Title"] = "Closet";
    Layout = "~/Views/Shared/_Layout.cshtml";    
}
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>  
</head>

<div class="text-center" text-align: center;>
    <img src="~/imgs/slogam.png" width=250 height=150 runat="server" ;>
    @if (@ViewBag.CurrentUser is not null)
       {
        <h1 class="display-6">Seja Bem Vindo(a), @ViewBag.CurrentUser.Name!!</h1>
       }
    else{
    <h1 class="display-6">Seja Bem Vindo(a)!!</h1>

       }

    <p> 


    </p>
    <button type="button" class="btn btn-primary btn-add-piece">Adicionar Peça</button>

    <div class="row">
        < class="col-md-4">
        <form asp-controller="ClosetController" asp-action="RegisterCloset" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nickname" class="control-label">Apelido da Peça</label>
                    <input asp-for="Nickname" class="form-control" />
                    <span asp-validation-for="Nickname" class="text-danger"></span>
                </div>
                <div class="small-form-group">
                    <label asp-for="Color" class="control-label">Cor</label>
                    <input asp-for="Color" type="color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Size" class="control-label">Tamanho</label>
                    <input asp-for="Size" class="form-control" />
                    <span asp-validation-for="Size" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.DropDownListFor(model => model.Type, new SelectList(Enum.GetValues(typeof(ClotheType))), "Selecione o tipo da peça")
                </div>              
                <div class="form-group">
                    @Html.DropDownListFor(model => model.Tissue, new SelectList(Enum.GetValues(typeof(TissueType))), "Selecione o tipo do tecido")
                </div>
                <div class="form-group">
                <label asp-for="ImageFile">Enviar Imagem:</label>
                <input asp-for="ImageFile" type="file" name="ImageFile" accept="image/*" />
                </div>
                <b />
                <div class="form-group">
                    <input type="submit" value="Registrar" asp-action="RegisterCloset"  class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@if (@ViewBag.UserCloset is not null)
{
    <div class="profile-grid">
        @foreach (var cloth in @ViewBag.UserCloset.Clothes)
        {
            <div class="cloth-item">
                <p>@cloth.Nickname</p>
                <img class="image-size" src="data:image/png;base64,@cloth.Image" alt="Image">
                <div class="button-container">
                    <form asp-controller="MeuController" asp-action="Metodo1" method="post">
                        <button class="btn-add-piece" type="submit">EDITAR</button>
                    </form>
                    <form asp-controller="ClosetController" asp-action="ExcluirPeca" method="post">
                        <button class="btn-add-piece" type="submit">EXCLUIR</button>
                    </form>
                </div>
            </div>
        }
    </div>
}





@section scripts {
    <script>
        $(document).ready(function () {
            $('.row').hide(); // Oculta o formulário inicialmente

            $('.btn-add-piece').click(function () {
                $('.row').show(); // Mostra o formulário ao clicar no botão "Adicionar Peça"
            });
        });
    </script>
}

MyClosetWeb Codigo/MyClosetWeb/Views/Home/Index.cshtml
@model MyClosetWeb.Models.User

@{
    ViewData["Title"] = "Home Page";
}
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<div class="text-center" text-align: center;>
    <img src="~/imgs/slogam.png" width=250 height=150 runat="server" ;>
    <h1 class="display-6">Seja Bem Vindo(a)!</h1>
    <p> </p>
</div>

<div class="form-popup" id="myForm">
    <form class="form-container" asp-controller="RegisterPage"  method="post">
        <span class="close" onclick="closeForm()">&times;</span>

        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" type="email" class="form-control" />

        <label asp-for="Password" class="control-label">Senha</label>
        <input asp-for="Password" type="password" class="form-control" />
        
        <button type="submit" class="btn" asp-controller="RegisterPage" asp-action="CheckUser">Entrar</button>
        <button type="button" id="registerbtn" class="btn register" asp-controller="RegisterPage" asp-action="Register">Cadastrar</button>
    </form>
</div>

@section scripts {
    <script>
        $(function () {
            $("#registerbtn").click(function () {
                window.location.href = '@Url.Action("RegisterPage", "Home")';
            });
        });
    </script>
}

MyClosetWeb Codigo/MyClosetWeb/Views/Home/RegisterPage.cshtml
@model MyClosetWeb.Models.User

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RegisterPage</title>
</head>
<body>

<h4>Cadastre-se!</h4>
<hr />
<div class="row">
    <div class="col-md-4">
            <form asp-controller="RegisterPage" asp-action="RegisterPage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nome Completo</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email"type="email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Senha</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <b/>
           <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar a pagina inicial</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

MyClosetWeb Codigo/MyClosetWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyClosetWeb.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/imgs/logo.png" width=50 height=50 runat="server"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="topMenu">
                        <li>
                            <a class="topButtons" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li>
                            <a class="topButtons" asp-area="" asp-controller="Home" asp-action="Privacy">Contato</a>
                        </li>
                        <li>
                            <a class="topButtons" asp-area="" asp-controller="logout" asp-action="Privacy">Sair</a>
                        </li>
                        </>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <div class="float-container">
        <div class="float-child">

            <div class="vertical-menu">
                <ul id="buttons">
                    @if (Context.Request.Path == "/")
                    {
                        <li><a href="#" onclick="openForm()" class="active">Entre/Registre-se</a></li>
                    }

                    <li><a href="#">Categorias</a></li>
                    <li><a href="#">Meus Looks Favoritos</a></li>
                    <li><a href="#">Itens para doar</a></li>
                    <li><a href="#">Lista de Desejos</a></li>
                </ul>

            </div>
        </div>
        <div class="float-child">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>


    </div>

    <footer class="border-top  footer text-muted">
        <div class="container">
            &copy; 2023 - MyCloset - <a asp-area="" asp-controller="Home" asp-action="Privacy">Contato</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Scripts/HomeScripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>